DEBUG:root:

faillll failed at:	2016-05-03 13:14:44.183000



User: calebma

Inputs:

	[]

Script:	C:\Users\calebma\Desktop\faillll.py


ERROR:fail_test:global name 'all_rackball' is not defined
Traceback (most recent call last):
  File "\\Arcserver1\GIS\KLINGNER_PR\X11111474\ESRI\Tools\LittleRiverDD\llrd\utils\__init__.py", line 293, in passArgs
    f = function(*argv)
  File "\\arcserver1\GIS\_Resources\ESRI\Python\BMI_Library\fail_test.py", line 2, in fail
    all_rackball
NameError: global name 'all_rackball' is not defined
